version: "3.8"

services:
  postgres:
    image: postgres:15
    # image: ankane/pgvector:latest
    container_name: postgres
    ports:
      - "5532:5432"
    environment:
      POSTGRES_USER: n8n
      POSTGRES_PASSWORD: password
      POSTGRES_DB: n8n
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d

  pgvector:
    image: ankane/pgvector:latest
    container_name: pgvector
    ports:
      - "5533:5432"
    environment:
      POSTGRES_USER: n8n
      POSTGRES_PASSWORD: password
      POSTGRES_DB: n8n
    volumes:
      - pgvector_data:/var/lib/postgresql/data

  n8n:
    image: n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      GENERIC_TIMEZONE: Europe/Berlin
      TZ: Europe/Berlin
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: "true"
      N8N_RUNNERS_ENABLED: "true"
      N8N_TUNNEL: "true"
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: n8n
      DB_POSTGRESDB_USER: n8n
      DB_POSTGRESDB_PASSWORD: password
    depends_on:
      - postgres
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  postgres_data:
  pgvector_data:
  n8n_data: